### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by larry-xu** [mwhittaker/aries#1]
- [x] Parse operations from the user using some parser combinator library most likely.
- [x] Display the current phase of the algorithm.
- [x] Display the current position in the operations or in the log. 
- [x] set status of in-progress transactions to "aborted" at end of analysis phase rather than during `analysis_update`
- [x] CLR prevLSN is incorrect, needs fixing
- [x] I think buffer pool needs to be updated during UNDO? when undo'ing an update, just write the `before` data to the buffer pool
- [x] instead of the simulator just mutating a single state object, it would be awesome if states were immutable, so the simulator could return a list of states. Then the UI can just transition between the states
  - the simulate function should just output a list of `aries.State` objects
- [x] after getting the above to work, there should be some notion of a UI state which contains:

```
{
    aries_state: aries.State,
    ui_actions: string list
}
```

the `ui_actions` is just a list of human-readable actions the DB performs so that we can show the user what actions are causing the changes they see to the state e.g. 

```
['Operation: T1 writes value "foo" to page A',
 'Operation: T2 writes value "foo" to page B',
 'DB CRASHED! Starting recovery...',
 'Analysis: DPT and Txn Table recovered from checkpoint',
  ...]
```
- [ ] styling + ui fixes
  - [x] Show what portion of the log has been forced to disk.
  - [x] Add ui controls for transitioning between different states
  - [ ] Add missing log columns (e.g. undoNextLSN).
  - [ ] Assign a color to each transaction and color log entries accordingly? I find this useful, but maybe it'll look tacky?
  - [ ] Draw arrows connecting a log entry to its prevLSN? Might get too cluttered.

**Comment by mwhittaker** [comment]
I was thinking about updating the `aries.State` class to include much more metadata that would be nice for displaying on the frontend. For example, it could include a list of the operations, the operation being processed, the phase of the algorithm, the `ui_actions` mentioned above, etc.

**Comment by larry-xu** [comment]
Joe suggested adding a lock table as well: transaction id to held locks mapping

**Comment by larry-xu** [comment]
Closing this issue since most of the todos are finished

**Comment by mwhittaker** [comment]
:confetti_ball: :tada:
